version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "monthly"
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "monthly"
